### ISSUE TITLE
0.4.8 youtube issues

### ISSUE THREAD

**Issue by red9350** [a9lim/Raiko#3]
Getting a "🚫 Error loading: Video returned by YouTube isn't what was requested" message when trying to play a youtube video.

The logs don't say anything useful

**Comment by a9lim** [comment]
Apologies for the late reply - this seems like an issue with [lavaplayer's youtube source manager](https://github.com/lavalink-devs/lavaplayer/pull/88), which was recently fixed with https://github.com/lavalink-devs/youtube-source
